spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 970614
        url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=UTF-8
    jpa:
        show-sql: true